### ISSUE TITLE
2.4.3 niepoprawna sciezka do payu.js

### ISSUE THREAD

**Issue by tomekjordan** [PayU/plugin_magento#69]
Witam, w nowej wersji jest podana niepoprawna scieżka do js-a i generuje 2x 404 na checkoucie

JS jest w:
/skin/frontend/base/default/js/payu.js
a plik powinien być umieszczony w:
/skin/frontend/base/default/js/payu/payu.js

pozdr
Tomek

**Comment by regdos** [comment]
Dziękujemy za zgłoszenie. Problem występował też we wcześniejszej wersji pluginu. Od wersji 2.4.4 już problem nie będzie występował.
