### ISSUE TITLE
Literówka w numerze wersji modułu

### ISSUE THREAD

**Issue by dariuszmaciejewski** [PayU/plugin_magento#71]
https://github.com/PayU/plugin_magento/blob/master/app/code/community/PayU/Account/etc/config.xml#L5

jest:
```xml
<version>2.4.4<</version>
```

powinno być:
```xml
<version>2.4.4</version>
```

**Comment by regdos** [comment]
Poprawione https://github.com/PayU/plugin_magento/commit/feebf06a7ad167d5f304835b5a52fbe02b23fd96
